#<% require "kitchen-sync" %>
---
driver:
  name: docker
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "true") %>

provisioner:
  name: chef_zero

platforms:
  - name: amazon-2015
    driver_config:
      image: ambakshi/amazon-linux
      platform: rhel
  - name: centos-6.6
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.0
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  <% %w[5.5 5.6].each do |version| %>
  - name: client_<%= version.tr(".", "") %>
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "<%= version %>"
    run_list:
      - recipe[percona::client]
      - recipe[percona::toolkit]

  - name: server_<%= version.tr(".", "") %>
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "<%= version %>"
        server:
          datadir: /tmp/mysql
          debian_password: d3b1an
          jemalloc: true
          root_password: r00t
    run_list:
      - recipe[percona::server]
      - recipe[percona::backup]
  <% end %>
