---
language: ruby

rvm:
# Use the version from the Chef Omnibus installer:
# https://github.com/opscode/omnibus-software/blob/master/config/software/ruby.rb#L19
- 1.9.3-p429

gemfile:
- test/support/Gemfile

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "FI7nEQHyd0YG0NJTQ1ENLEnFAOZRPetmd5FbOOp9WYNdTbbTkWzYXHWHdTxg\nlLdnCeqtArDb+UJvnnS+jWamBULZqNktz0qYdSGs4JVgFa8VsU7j/k172EF9\ngaBOWZ8H/Pin1pFccDHjy5dFXBLcB5k0awM+LDlhbZdlQgD9+qo="
  # AWS_SECRET_ACCESS_KEY
  - secure: "hKI4e2WqXmNpiabTCN1bBB00w3HEaR3khOnp5YKuSJCO0zsyhJMdTI9X9ynB\ncvQvddI8lWbkfTvsEGed+QBummzGHJ34Gao/cYCxWnoMpGmFtBhk60/du/ep\nLYWGnCbbFq9L6i6Or1Q2649q/OjYUgJd3C8/WjI0S6K5Qzyv/XQ="

script:
- bundle exec rake knife
- bundle exec rake foodcritic
- bundle exec kitchen test --parallel --destroy=always

branches:
  only:
  - master

notifications:
  email: false
